### ISSUE TITLE
what does '\"]\|[\"]/.*[' on line 77 checks for ?

### ISSUE THREAD

**Issue by harsh-98** [UltimateHackers/Diggy#1]

**Comment by UltimateHackers** [comment]
The complete regex pattern is:
```
['\"]http.*//.*['\"]\|['\"]/.*['\"]
```
- `['\"]` matches either ' or " which are mostly used to contain variables.
- `http.*//` matches anything having `http` and `//`
- `.*['\"]` is again for matching everything until a ' or " occurs.
- `\|` is used for using multiple patterns.
The first pattern (before the `\|`) will match strings enclosed within " and ' and starting with http.
Second pattern is quite similar except the fact that it tries to look for the strings of following kind:
`"/db/api/mobile"`
